package com.example.entity;

public class AdministratorInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column administrator.ID
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	private String ID;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column administrator.username
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column administrator.passwords
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	private String passwords;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column administrator.A_struts
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	private Integer A_struts;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column administrator.ID
	 * @return  the value of administrator.ID
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public String getID() {
		return ID;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column administrator.ID
	 * @param ID  the value for administrator.ID
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public void setID(String ID) {
		this.ID = ID == null ? null : ID.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column administrator.username
	 * @return  the value of administrator.username
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column administrator.username
	 * @param username  the value for administrator.username
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public void setUsername(String username) {
		this.username = username == null ? null : username.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column administrator.passwords
	 * @return  the value of administrator.passwords
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public String getPasswords() {
		return passwords;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column administrator.passwords
	 * @param passwords  the value for administrator.passwords
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public void setPasswords(String passwords) {
		this.passwords = passwords == null ? null : passwords.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column administrator.A_struts
	 * @return  the value of administrator.A_struts
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public Integer getA_struts() {
		return A_struts;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column administrator.A_struts
	 * @param integer  the value for administrator.A_struts
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public void setA_struts(Integer integer) {
		this.A_struts = integer;
	}
}