package com.example.entity;

import java.math.BigDecimal;


public class AllclassInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column allclass.CL_ID
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	private Integer CL_ID;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column allclass.CO_ID
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	private Integer CO_ID;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column allclass.ID
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	private String ID;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column allclass.CL_name
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	private String CL_name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column allclass.CL_capacity
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	private Integer CL_capacity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column allclass.CL_number
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	private Integer CL_number;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column allclass.CL_price
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	private BigDecimal CL_price;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column allclass.CL_startTime
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	private Long CL_startTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column allclass.CL_endTime
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	private Long CL_endTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column allclass.CL_ID
	 * @return  the value of allclass.CL_ID
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public Integer getCL_ID() {
		return CL_ID;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column allclass.CL_ID
	 * @param CL_ID  the value for allclass.CL_ID
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public void setCL_ID(Integer CL_ID) {
		this.CL_ID = CL_ID;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column allclass.CO_ID
	 * @return  the value of allclass.CO_ID
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public Integer getCO_ID() {
		return CO_ID;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column allclass.CO_ID
	 * @param CO_ID  the value for allclass.CO_ID
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public void setCO_ID(Integer CO_ID) {
		this.CO_ID = CO_ID;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column allclass.ID
	 * @return  the value of allclass.ID
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public String getID() {
		return ID;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column allclass.ID
	 * @param ID  the value for allclass.ID
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public void setID(String ID) {
		this.ID = ID == null ? null : ID.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column allclass.CL_name
	 * @return  the value of allclass.CL_name
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public String getCL_name() {
		return CL_name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column allclass.CL_name
	 * @param CL_name  the value for allclass.CL_name
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public void setCL_name(String CL_name) {
		this.CL_name = CL_name == null ? null : CL_name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column allclass.CL_capacity
	 * @return  the value of allclass.CL_capacity
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public Integer getCL_capacity() {
		return CL_capacity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column allclass.CL_capacity
	 * @param integer  the value for allclass.CL_capacity
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public void setCL_capacity(Integer integer) {
		this.CL_capacity = integer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column allclass.CL_number
	 * @return  the value of allclass.CL_number
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public Integer getCL_number() {
		return CL_number;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column allclass.CL_number
	 * @param integer  the value for allclass.CL_number
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public void setCL_number(Integer integer) {
		this.CL_number = integer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column allclass.CL_price
	 * @return  the value of allclass.CL_price
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public BigDecimal getCL_price() {
		return CL_price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column allclass.CL_price
	 * @param CL_price  the value for allclass.CL_price
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public void setCL_price(BigDecimal CL_price) {
		this.CL_price = CL_price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column allclass.CL_startTime
	 * @return  the value of allclass.CL_startTime
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public Long getCL_startTime() {
		return CL_startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column allclass.CL_startTime
	 * @param CL_startTime  the value for allclass.CL_startTime
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public void setCL_startTime(Long CL_startTime) {
		this.CL_startTime = CL_startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column allclass.CL_endTime
	 * @return  the value of allclass.CL_endTime
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public Long getCL_endTime() {
		return CL_endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column allclass.CL_endTime
	 * @param CL_endTime  the value for allclass.CL_endTime
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public void setCL_endTime(Long CL_endTime) {
		this.CL_endTime = CL_endTime;
	}
}