package com.example.entity;

public class HomeworktestInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column homeworktest.HT_ID
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	private Integer HT_ID;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column homeworktest.L_ID
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	private Integer L_ID;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column homeworktest.HT_form
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	private String HT_form;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column homeworktest.HT_introduction
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	private String HT_introduction;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column homeworktest.HT_startTime
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	private Long HT_startTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column homeworktest.HT_endTime
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	private Long HT_endTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column homeworktest.HT_ID
	 * @return  the value of homeworktest.HT_ID
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public Integer getHT_ID() {
		return HT_ID;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column homeworktest.HT_ID
	 * @param HT_ID  the value for homeworktest.HT_ID
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public void setHT_ID(Integer HT_ID) {
		this.HT_ID = HT_ID;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column homeworktest.L_ID
	 * @return  the value of homeworktest.L_ID
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public Integer getL_ID() {
		return L_ID;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column homeworktest.L_ID
	 * @param L_ID  the value for homeworktest.L_ID
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public void setL_ID(Integer L_ID) {
		this.L_ID = L_ID;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column homeworktest.HT_form
	 * @return  the value of homeworktest.HT_form
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public String getHT_form() {
		return HT_form;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column homeworktest.HT_form
	 * @param HT_form  the value for homeworktest.HT_form
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public void setHT_form(String HT_form) {
		this.HT_form = HT_form == null ? null : HT_form.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column homeworktest.HT_introduction
	 * @return  the value of homeworktest.HT_introduction
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public String getHT_introduction() {
		return HT_introduction;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column homeworktest.HT_introduction
	 * @param HT_introduction  the value for homeworktest.HT_introduction
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public void setHT_introduction(String HT_introduction) {
		this.HT_introduction = HT_introduction == null ? null : HT_introduction.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column homeworktest.HT_startTime
	 * @return  the value of homeworktest.HT_startTime
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public Long getHT_startTime() {
		return HT_startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column homeworktest.HT_startTime
	 * @param HT_startTime  the value for homeworktest.HT_startTime
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public void setHT_startTime(Long HT_startTime) {
		this.HT_startTime = HT_startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column homeworktest.HT_endTime
	 * @return  the value of homeworktest.HT_endTime
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public Long getHT_endTime() {
		return HT_endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column homeworktest.HT_endTime
	 * @param HT_endTime  the value for homeworktest.HT_endTime
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public void setHT_endTime(Long HT_endTime) {
		this.HT_endTime = HT_endTime;
	}
}