package com.example.entity;

public class LessonInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lesson.L_ID
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	private Integer L_ID;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lesson.CL_ID
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	private Integer CL_ID;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lesson.L_name
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	private String L_name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lesson.L_introduction
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	private String L_introduction;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lesson.L_startTime
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	private Long L_startTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lesson.L_endTime
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	private Long L_endTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lesson.L_ID
	 * @return  the value of lesson.L_ID
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public Integer getL_ID() {
		return L_ID;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lesson.L_ID
	 * @param L_ID  the value for lesson.L_ID
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public void setL_ID(Integer L_ID) {
		this.L_ID = L_ID;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lesson.CL_ID
	 * @return  the value of lesson.CL_ID
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public Integer getCL_ID() {
		return CL_ID;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lesson.CL_ID
	 * @param CL_ID  the value for lesson.CL_ID
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public void setCL_ID(Integer CL_ID) {
		this.CL_ID = CL_ID;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lesson.L_name
	 * @return  the value of lesson.L_name
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public String getL_name() {
		return L_name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lesson.L_name
	 * @param L_name  the value for lesson.L_name
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public void setL_name(String L_name) {
		this.L_name = L_name == null ? null : L_name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lesson.L_introduction
	 * @return  the value of lesson.L_introduction
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public String getL_introduction() {
		return L_introduction;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lesson.L_introduction
	 * @param L_introduction  the value for lesson.L_introduction
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public void setL_introduction(String L_introduction) {
		this.L_introduction = L_introduction == null ? null : L_introduction.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lesson.L_startTime
	 * @return  the value of lesson.L_startTime
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public Long getL_startTime() {
		return L_startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lesson.L_startTime
	 * @param L_startTime  the value for lesson.L_startTime
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public void setL_startTime(Long L_startTime) {
		this.L_startTime = L_startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lesson.L_endTime
	 * @return  the value of lesson.L_endTime
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public Long getL_endTime() {
		return L_endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lesson.L_endTime
	 * @param L_endTime  the value for lesson.L_endTime
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public void setL_endTime(Long L_endTime) {
		this.L_endTime = L_endTime;
	}
}