package com.example.entity;

public class OrdersInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orders.ID
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	private String ID;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orders.CL_ID
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	private Integer CL_ID;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orders.O_Time
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	private Long O_Time;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orders.ID
	 * @return  the value of orders.ID
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public String getID() {
		return ID;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orders.ID
	 * @param ID  the value for orders.ID
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public void setID(String ID) {
		this.ID = ID == null ? null : ID.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orders.CL_ID
	 * @return  the value of orders.CL_ID
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public Integer getCL_ID() {
		return CL_ID;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orders.CL_ID
	 * @param CL_ID  the value for orders.CL_ID
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public void setCL_ID(Integer CL_ID) {
		this.CL_ID = CL_ID;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orders.O_Time
	 * @return  the value of orders.O_Time
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public Long getO_Time() {
		return O_Time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orders.O_Time
	 * @param O_Time  the value for orders.O_Time
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public void setO_Time(Long O_Time) {
		this.O_Time = O_Time;
	}
}