package com.example.entity;

public class ResourcesInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resources.RE_ID
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	private Integer RE_ID;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resources.L_ID
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	private Integer L_ID;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resources.RE_form
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	private String RE_form;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resources.RE_introduction
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	private String RE_introduction;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resources.RE_ID
	 * @return  the value of resources.RE_ID
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public Integer getRE_ID() {
		return RE_ID;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resources.RE_ID
	 * @param RE_ID  the value for resources.RE_ID
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public void setRE_ID(Integer RE_ID) {
		this.RE_ID = RE_ID;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resources.L_ID
	 * @return  the value of resources.L_ID
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public Integer getL_ID() {
		return L_ID;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resources.L_ID
	 * @param L_ID  the value for resources.L_ID
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public void setL_ID(Integer L_ID) {
		this.L_ID = L_ID;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resources.RE_form
	 * @return  the value of resources.RE_form
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public String getRE_form() {
		return RE_form;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resources.RE_form
	 * @param RE_form  the value for resources.RE_form
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public void setRE_form(String RE_form) {
		this.RE_form = RE_form == null ? null : RE_form.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resources.RE_introduction
	 * @return  the value of resources.RE_introduction
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public String getRE_introduction() {
		return RE_introduction;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resources.RE_introduction
	 * @param RE_introduction  the value for resources.RE_introduction
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public void setRE_introduction(String RE_introduction) {
		this.RE_introduction = RE_introduction == null ? null : RE_introduction.trim();
	}
}