package com.example.entity;

public class ScInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sc.STU_ID
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	private String STU_ID;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sc.CL_ID
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	private Integer CL_ID;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sc.ID
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	private String ID;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sc.STU_ID
	 * @return  the value of sc.STU_ID
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public String getSTU_ID() {
		return STU_ID;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sc.STU_ID
	 * @param STU_ID  the value for sc.STU_ID
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public void setSTU_ID(String STU_ID) {
		this.STU_ID = STU_ID == null ? null : STU_ID.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sc.CL_ID
	 * @return  the value of sc.CL_ID
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public Integer getCL_ID() {
		return CL_ID;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sc.CL_ID
	 * @param CL_ID  the value for sc.CL_ID
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public void setCL_ID(Integer CL_ID) {
		this.CL_ID = CL_ID;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sc.ID
	 * @return  the value of sc.ID
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public String getID() {
		return ID;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sc.ID
	 * @param ID  the value for sc.ID
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public void setID(String ID) {
		this.ID = ID == null ? null : ID.trim();
	}
}