package com.example.entity;

public class StudentInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column student.ID
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	private String ID;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column student.username
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column student.passwords
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	private String passwords;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column student.S_name
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	private String S_name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column student.S_sex
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	private String S_sex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column student.S_IDcard
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	private String S_IDcard;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column student.S_introduction
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	private String S_introduction;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column student.S_qq
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	private String S_qq;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column student.S_wei
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	private String S_wei;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column student.S_emile
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	private String S_emile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column student.S_mobile
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	private Long S_mobile;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column student.ID
	 * @return  the value of student.ID
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public String getID() {
		return ID;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column student.ID
	 * @param ID  the value for student.ID
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public void setID(String ID) {
		this.ID = ID == null ? null : ID.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column student.username
	 * @return  the value of student.username
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column student.username
	 * @param username  the value for student.username
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public void setUsername(String username) {
		this.username = username == null ? null : username.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column student.passwords
	 * @return  the value of student.passwords
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public String getPasswords() {
		return passwords;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column student.passwords
	 * @param passwords  the value for student.passwords
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public void setPasswords(String passwords) {
		this.passwords = passwords == null ? null : passwords.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column student.S_name
	 * @return  the value of student.S_name
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public String getS_name() {
		return S_name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column student.S_name
	 * @param S_name  the value for student.S_name
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public void setS_name(String S_name) {
		this.S_name = S_name == null ? null : S_name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column student.S_sex
	 * @return  the value of student.S_sex
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public String getS_sex() {
		return S_sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column student.S_sex
	 * @param S_sex  the value for student.S_sex
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public void setS_sex(String S_sex) {
		this.S_sex = S_sex == null ? null : S_sex.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column student.S_IDcard
	 * @return  the value of student.S_IDcard
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public String getS_IDcard() {
		return S_IDcard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column student.S_IDcard
	 * @param S_IDcard  the value for student.S_IDcard
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public void setS_IDcard(String S_IDcard) {
		this.S_IDcard = S_IDcard == null ? null : S_IDcard.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column student.S_introduction
	 * @return  the value of student.S_introduction
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public String getS_introduction() {
		return S_introduction;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column student.S_introduction
	 * @param S_introduction  the value for student.S_introduction
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public void setS_introduction(String S_introduction) {
		this.S_introduction = S_introduction == null ? null : S_introduction.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column student.S_qq
	 * @return  the value of student.S_qq
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public String getS_qq() {
		return S_qq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column student.S_qq
	 * @param S_qq  the value for student.S_qq
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public void setS_qq(String S_qq) {
		this.S_qq = S_qq == null ? null : S_qq.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column student.S_wei
	 * @return  the value of student.S_wei
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public String getS_wei() {
		return S_wei;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column student.S_wei
	 * @param S_wei  the value for student.S_wei
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public void setS_wei(String S_wei) {
		this.S_wei = S_wei == null ? null : S_wei.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column student.S_emile
	 * @return  the value of student.S_emile
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public String getS_emile() {
		return S_emile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column student.S_emile
	 * @param S_emile  the value for student.S_emile
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public void setS_emile(String S_emile) {
		this.S_emile = S_emile == null ? null : S_emile.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column student.S_mobile
	 * @return  the value of student.S_mobile
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public Long getS_mobile() {
		return S_mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column student.S_mobile
	 * @param S_mobile  the value for student.S_mobile
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public void setS_mobile(Long S_mobile) {
		this.S_mobile = S_mobile;
	}
}