package com.example.entity;

public class TeacherInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column teacher.ID
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	private String ID;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column teacher.username
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column teacher.passwords
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	private String passwords;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column teacher.T_name
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	private String T_name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column teacher.T_sex
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	private String T_sex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column teacher.T_Cnumber
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	private String T_Cnumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column teacher.T_introduction
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	private String T_introduction;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column teacher.T_IDcard
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	private String T_IDcard;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column teacher.T_QQ
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	private String T_QQ;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column teacher.T_wei
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	private String T_wei;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column teacher.T_emile
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	private String T_emile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column teacher.T_mobile
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	private Long T_mobile;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column teacher.ID
	 * @return  the value of teacher.ID
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public String getID() {
		return ID;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column teacher.ID
	 * @param ID  the value for teacher.ID
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public void setID(String ID) {
		this.ID = ID == null ? null : ID.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column teacher.username
	 * @return  the value of teacher.username
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column teacher.username
	 * @param username  the value for teacher.username
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public void setUsername(String username) {
		this.username = username == null ? null : username.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column teacher.passwords
	 * @return  the value of teacher.passwords
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public String getPasswords() {
		return passwords;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column teacher.passwords
	 * @param passwords  the value for teacher.passwords
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public void setPasswords(String passwords) {
		this.passwords = passwords == null ? null : passwords.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column teacher.T_name
	 * @return  the value of teacher.T_name
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public String getT_name() {
		return T_name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column teacher.T_name
	 * @param T_name  the value for teacher.T_name
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public void setT_name(String T_name) {
		this.T_name = T_name == null ? null : T_name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column teacher.T_sex
	 * @return  the value of teacher.T_sex
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public String getT_sex() {
		return T_sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column teacher.T_sex
	 * @param T_sex  the value for teacher.T_sex
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public void setT_sex(String T_sex) {
		this.T_sex = T_sex == null ? null : T_sex.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column teacher.T_Cnumber
	 * @return  the value of teacher.T_Cnumber
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public String getT_Cnumber() {
		return T_Cnumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column teacher.T_Cnumber
	 * @param T_Cnumber  the value for teacher.T_Cnumber
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public void setT_Cnumber(String T_Cnumber) {
		this.T_Cnumber = T_Cnumber == null ? null : T_Cnumber.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column teacher.T_introduction
	 * @return  the value of teacher.T_introduction
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public String getT_introduction() {
		return T_introduction;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column teacher.T_introduction
	 * @param T_introduction  the value for teacher.T_introduction
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public void setT_introduction(String T_introduction) {
		this.T_introduction = T_introduction == null ? null : T_introduction.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column teacher.T_IDcard
	 * @return  the value of teacher.T_IDcard
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public String getT_IDcard() {
		return T_IDcard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column teacher.T_IDcard
	 * @param T_IDcard  the value for teacher.T_IDcard
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public void setT_IDcard(String T_IDcard) {
		this.T_IDcard = T_IDcard == null ? null : T_IDcard.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column teacher.T_QQ
	 * @return  the value of teacher.T_QQ
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public String getT_QQ() {
		return T_QQ;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column teacher.T_QQ
	 * @param T_QQ  the value for teacher.T_QQ
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public void setT_QQ(String T_QQ) {
		this.T_QQ = T_QQ == null ? null : T_QQ.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column teacher.T_wei
	 * @return  the value of teacher.T_wei
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public String getT_wei() {
		return T_wei;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column teacher.T_wei
	 * @param T_wei  the value for teacher.T_wei
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public void setT_wei(String T_wei) {
		this.T_wei = T_wei == null ? null : T_wei.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column teacher.T_emile
	 * @return  the value of teacher.T_emile
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public String getT_emile() {
		return T_emile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column teacher.T_emile
	 * @param T_emile  the value for teacher.T_emile
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public void setT_emile(String T_emile) {
		this.T_emile = T_emile == null ? null : T_emile.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column teacher.T_mobile
	 * @return  the value of teacher.T_mobile
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public Long getT_mobile() {
		return T_mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column teacher.T_mobile
	 * @param T_mobile  the value for teacher.T_mobile
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public void setT_mobile(Long T_mobile) {
		this.T_mobile = T_mobile;
	}
}