package com.example.entity;

public class UsersInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.ID
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	private String ID;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.username
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.passwords
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	private String passwords;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.ID
	 * @return  the value of users.ID
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public String getID() {
		return ID;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.ID
	 * @param ID  the value for users.ID
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public void setID(String ID) {
		this.ID = ID == null ? null : ID.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.username
	 * @return  the value of users.username
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.username
	 * @param username  the value for users.username
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public void setUsername(String username) {
		this.username = username == null ? null : username.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.passwords
	 * @return  the value of users.passwords
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public String getPasswords() {
		return passwords;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.passwords
	 * @param passwords  the value for users.passwords
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public void setPasswords(String passwords) {
		this.passwords = passwords == null ? null : passwords.trim();
	}
}