package com.example.mapper;

import com.example.entity.AdjustmentInfo;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface AdjustmentInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table adjustment
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	@Delete({ "delete from adjustment", "where AD_ID = #{AD_ID,jdbcType=DECIMAL}" })
	int deleteByPrimaryKey(Integer AD_ID);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table adjustment
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	@Insert({ "insert into adjustment (AD_ID, ID, ", "STU_ID, AD_time, ", "AD_introduction)",
			"values (#{AD_ID,jdbcType=DECIMAL}, #{ID,jdbcType=VARCHAR}, ",
			"#{STU_ID,jdbcType=VARCHAR}, #{AD_time,jdbcType=DECIMAL}, ", "#{AD_introduction,jdbcType=VARCHAR})" })
	int insert(AdjustmentInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table adjustment
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	@InsertProvider(type = AdjustmentInfoSqlProvider.class, method = "insertSelective")
	int insertSelective(AdjustmentInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table adjustment
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	@Select({ "select", "AD_ID, ID, STU_ID, AD_time, AD_introduction", "from adjustment",
			"where AD_ID = #{AD_ID,jdbcType=DECIMAL}" })
	@Results({ @Result(column = "AD_ID", property = "AD_ID", jdbcType = JdbcType.DECIMAL, id = true),
			@Result(column = "ID", property = "ID", jdbcType = JdbcType.VARCHAR),
			@Result(column = "STU_ID", property = "STU_ID", jdbcType = JdbcType.VARCHAR),
			@Result(column = "AD_time", property = "AD_time", jdbcType = JdbcType.DECIMAL),
			@Result(column = "AD_introduction", property = "AD_introduction", jdbcType = JdbcType.VARCHAR) })
	AdjustmentInfo selectByPrimaryKey(Integer AD_ID);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table adjustment
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	@UpdateProvider(type = AdjustmentInfoSqlProvider.class, method = "updateByPrimaryKeySelective")
	int updateByPrimaryKeySelective(AdjustmentInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table adjustment
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	@Update({ "update adjustment", "set ID = #{ID,jdbcType=VARCHAR},", "STU_ID = #{STU_ID,jdbcType=VARCHAR},",
			"AD_time = #{AD_time,jdbcType=DECIMAL},", "AD_introduction = #{AD_introduction,jdbcType=VARCHAR}",
			"where AD_ID = #{AD_ID,jdbcType=DECIMAL}" })
	int updateByPrimaryKey(AdjustmentInfo record);
}