package com.example.mapper;

import com.example.entity.AdjustmentInfo;
import org.apache.ibatis.jdbc.SQL;

public class AdjustmentInfoSqlProvider {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table adjustment
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public String insertSelective(AdjustmentInfo record) {
		SQL sql = new SQL();
		sql.INSERT_INTO("adjustment");
		if (record.getAD_ID() != null) {
			sql.VALUES("AD_ID", "#{AD_ID,jdbcType=DECIMAL}");
		}
		if (record.getID() != null) {
			sql.VALUES("ID", "#{ID,jdbcType=VARCHAR}");
		}
		if (record.getSTU_ID() != null) {
			sql.VALUES("STU_ID", "#{STU_ID,jdbcType=VARCHAR}");
		}
		if (record.getAD_time() != null) {
			sql.VALUES("AD_time", "#{AD_time,jdbcType=DECIMAL}");
		}
		if (record.getAD_introduction() != null) {
			sql.VALUES("AD_introduction", "#{AD_introduction,jdbcType=VARCHAR}");
		}
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table adjustment
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public String updateByPrimaryKeySelective(AdjustmentInfo record) {
		SQL sql = new SQL();
		sql.UPDATE("adjustment");
		if (record.getID() != null) {
			sql.SET("ID = #{ID,jdbcType=VARCHAR}");
		}
		if (record.getSTU_ID() != null) {
			sql.SET("STU_ID = #{STU_ID,jdbcType=VARCHAR}");
		}
		if (record.getAD_time() != null) {
			sql.SET("AD_time = #{AD_time,jdbcType=DECIMAL}");
		}
		if (record.getAD_introduction() != null) {
			sql.SET("AD_introduction = #{AD_introduction,jdbcType=VARCHAR}");
		}
		sql.WHERE("AD_ID = #{AD_ID,jdbcType=DECIMAL}");
		return sql.toString();
	}
}