package com.example.mapper;

import com.example.entity.AdministratorInfo;
import org.apache.ibatis.jdbc.SQL;

public class AdministratorInfoSqlProvider {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table administrator
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public String insertSelective(AdministratorInfo record) {
		SQL sql = new SQL();
		sql.INSERT_INTO("administrator");
		if (record.getID() != null) {
			sql.VALUES("ID", "#{ID,jdbcType=VARCHAR}");
		}
		if (record.getUsername() != null) {
			sql.VALUES("username", "#{username,jdbcType=VARCHAR}");
		}
		if (record.getPasswords() != null) {
			sql.VALUES("passwords", "#{passwords,jdbcType=VARCHAR}");
		}
		if (record.getA_struts() != null) {
			sql.VALUES("A_struts", "#{A_struts,jdbcType=DECIMAL}");
		}
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table administrator
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public String updateByPrimaryKeySelective(AdministratorInfo record) {
		SQL sql = new SQL();
		sql.UPDATE("administrator");
		if (record.getUsername() != null) {
			sql.SET("username = #{username,jdbcType=VARCHAR}");
		}
		if (record.getPasswords() != null) {
			sql.SET("passwords = #{passwords,jdbcType=VARCHAR}");
		}
		if (record.getA_struts() != null) {
			sql.SET("A_struts = #{A_struts,jdbcType=DECIMAL}");
		}
		sql.WHERE("ID = #{ID,jdbcType=VARCHAR}");
		return sql.toString();
	}
}