package com.example.mapper;

import com.example.entity.AllclassInfo;
import org.apache.ibatis.jdbc.SQL;

public class AllclassInfoSqlProvider {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table allclass
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public String insertSelective(AllclassInfo record) {
		SQL sql = new SQL();
		sql.INSERT_INTO("allclass");
		if (record.getCL_ID() != null) {
			sql.VALUES("CL_ID", "#{CL_ID,jdbcType=DECIMAL}");
		}
		if (record.getCO_ID() != null) {
			sql.VALUES("CO_ID", "#{CO_ID,jdbcType=DECIMAL}");
		}
		if (record.getID() != null) {
			sql.VALUES("ID", "#{ID,jdbcType=VARCHAR}");
		}
		if (record.getCL_name() != null) {
			sql.VALUES("CL_name", "#{CL_name,jdbcType=VARCHAR}");
		}
		if (record.getCL_capacity() != null) {
			sql.VALUES("CL_capacity", "#{CL_capacity,jdbcType=DECIMAL}");
		}
		if (record.getCL_number() != null) {
			sql.VALUES("CL_number", "#{CL_number,jdbcType=DECIMAL}");
		}
		if (record.getCL_price() != null) {
			sql.VALUES("CL_price", "#{CL_price,jdbcType=DECIMAL}");
		}
		if (record.getCL_startTime() != null) {
			sql.VALUES("CL_startTime", "#{CL_startTime,jdbcType=DECIMAL}");
		}
		if (record.getCL_endTime() != null) {
			sql.VALUES("CL_endTime", "#{CL_endTime,jdbcType=DECIMAL}");
		}
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table allclass
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public String updateByPrimaryKeySelective(AllclassInfo record) {
		SQL sql = new SQL();
		sql.UPDATE("allclass");
		if (record.getCO_ID() != null) {
			sql.SET("CO_ID = #{CO_ID,jdbcType=DECIMAL}");
		}
		if (record.getID() != null) {
			sql.SET("ID = #{ID,jdbcType=VARCHAR}");
		}
		if (record.getCL_name() != null) {
			sql.SET("CL_name = #{CL_name,jdbcType=VARCHAR}");
		}
		if (record.getCL_capacity() != null) {
			sql.SET("CL_capacity = #{CL_capacity,jdbcType=DECIMAL}");
		}
		if (record.getCL_number() != null) {
			sql.SET("CL_number = #{CL_number,jdbcType=DECIMAL}");
		}
		if (record.getCL_price() != null) {
			sql.SET("CL_price = #{CL_price,jdbcType=DECIMAL}");
		}
		if (record.getCL_startTime() != null) {
			sql.SET("CL_startTime = #{CL_startTime,jdbcType=DECIMAL}");
		}
		if (record.getCL_endTime() != null) {
			sql.SET("CL_endTime = #{CL_endTime,jdbcType=DECIMAL}");
		}
		sql.WHERE("CL_ID = #{CL_ID,jdbcType=DECIMAL}");
		return sql.toString();
	}
}