package com.example.mapper;

import com.example.entity.CommentsInfo;
import org.apache.ibatis.jdbc.SQL;

public class CommentsInfoSqlProvider {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comments
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public String insertSelective(CommentsInfo record) {
		SQL sql = new SQL();
		sql.INSERT_INTO("comments");
		if (record.getCOM_ID() != null) {
			sql.VALUES("COM_ID", "#{COM_ID,jdbcType=VARCHAR}");
		}
		if (record.getL_ID() != null) {
			sql.VALUES("L_ID", "#{L_ID,jdbcType=DECIMAL}");
		}
		if (record.getID() != null) {
			sql.VALUES("ID", "#{ID,jdbcType=VARCHAR}");
		}
		if (record.getCOM_information() != null) {
			sql.VALUES("COM_information", "#{COM_information,jdbcType=VARCHAR}");
		}
		if (record.getCOM_time() != null) {
			sql.VALUES("COM_time", "#{COM_time,jdbcType=DECIMAL}");
		}
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comments
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public String updateByPrimaryKeySelective(CommentsInfo record) {
		SQL sql = new SQL();
		sql.UPDATE("comments");
		if (record.getL_ID() != null) {
			sql.SET("L_ID = #{L_ID,jdbcType=DECIMAL}");
		}
		if (record.getID() != null) {
			sql.SET("ID = #{ID,jdbcType=VARCHAR}");
		}
		if (record.getCOM_information() != null) {
			sql.SET("COM_information = #{COM_information,jdbcType=VARCHAR}");
		}
		if (record.getCOM_time() != null) {
			sql.SET("COM_time = #{COM_time,jdbcType=DECIMAL}");
		}
		sql.WHERE("COM_ID = #{COM_ID,jdbcType=VARCHAR}");
		return sql.toString();
	}
}