package com.example.mapper;

import com.example.entity.CoursesInfo;
import org.apache.ibatis.jdbc.SQL;

public class CoursesInfoSqlProvider {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table courses
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public String insertSelective(CoursesInfo record) {
		SQL sql = new SQL();
		sql.INSERT_INTO("courses");
		if (record.getCO_ID() != null) {
			sql.VALUES("CO_ID", "#{CO_ID,jdbcType=DECIMAL}");
		}
		if (record.getM_ID() != null) {
			sql.VALUES("M_ID", "#{M_ID,jdbcType=DECIMAL}");
		}
		if (record.getCO_name() != null) {
			sql.VALUES("CO_name", "#{CO_name,jdbcType=VARCHAR}");
		}
		if (record.getCO_introduction() != null) {
			sql.VALUES("CO_introduction", "#{CO_introduction,jdbcType=VARCHAR}");
		}
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table courses
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public String updateByPrimaryKeySelective(CoursesInfo record) {
		SQL sql = new SQL();
		sql.UPDATE("courses");
		if (record.getM_ID() != null) {
			sql.SET("M_ID = #{M_ID,jdbcType=DECIMAL}");
		}
		if (record.getCO_name() != null) {
			sql.SET("CO_name = #{CO_name,jdbcType=VARCHAR}");
		}
		if (record.getCO_introduction() != null) {
			sql.SET("CO_introduction = #{CO_introduction,jdbcType=VARCHAR}");
		}
		sql.WHERE("CO_ID = #{CO_ID,jdbcType=DECIMAL}");
		return sql.toString();
	}
}