package com.example.mapper;

import com.example.entity.CoursesInfo;
import com.example.object.CoursesObject;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface CoursesInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table courses
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	@Delete({ "delete from courses", "where CO_ID = #{CO_ID,jdbcType=DECIMAL}" })
	int deleteByPrimaryKey(Integer CO_ID);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table courses
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	@Insert({ "insert into courses (CO_ID, M_ID, ", "CO_name, CO_introduction)",
			"values (#{CO_ID,jdbcType=DECIMAL}, #{M_ID,jdbcType=DECIMAL}, ",
			"#{CO_name,jdbcType=VARCHAR}, #{CO_introduction,jdbcType=VARCHAR})" })
	int insert(CoursesInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table courses
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	@InsertProvider(type = CoursesInfoSqlProvider.class, method = "insertSelective")
	int insertSelective(CoursesInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table courses
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	@Select({ "select", "CO_ID, M_ID, CO_name, CO_introduction", "from courses",
			"where CO_ID = #{CO_ID,jdbcType=DECIMAL}" })
	@Results({ @Result(column = "CO_ID", property = "CO_ID", jdbcType = JdbcType.DECIMAL, id = true),
			@Result(column = "M_ID", property = "M_ID", jdbcType = JdbcType.DECIMAL),
			@Result(column = "CO_name", property = "CO_name", jdbcType = JdbcType.VARCHAR),
			@Result(column = "CO_introduction", property = "CO_introduction", jdbcType = JdbcType.VARCHAR) })
	CoursesObject selectByPrimaryKey(Integer CO_ID);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table courses
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	@UpdateProvider(type = CoursesInfoSqlProvider.class, method = "updateByPrimaryKeySelective")
	int updateByPrimaryKeySelective(CoursesInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table courses
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	@Update({ "update courses", "set M_ID = #{M_ID,jdbcType=DECIMAL},", "CO_name = #{CO_name,jdbcType=VARCHAR},",
			"CO_introduction = #{CO_introduction,jdbcType=VARCHAR}", "where CO_ID = #{CO_ID,jdbcType=DECIMAL}" })
	int updateByPrimaryKey(CoursesInfo record);
}