package com.example.mapper;

import com.example.entity.HomeworktestInfo;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface HomeworktestInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table homeworktest
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	@Delete({ "delete from homeworktest", "where HT_ID = #{HT_ID,jdbcType=DECIMAL}" })
	int deleteByPrimaryKey(Integer HT_ID);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table homeworktest
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	@Insert({ "insert into homeworktest (HT_ID, L_ID, ", "HT_form, HT_introduction, ", "HT_startTime, HT_endTime)",
			"values (#{HT_ID,jdbcType=DECIMAL}, #{L_ID,jdbcType=DECIMAL}, ",
			"#{HT_form,jdbcType=VARCHAR}, #{HT_introduction,jdbcType=VARCHAR}, ",
			"#{HT_startTime,jdbcType=DECIMAL}, #{HT_endTime,jdbcType=DECIMAL})" })
	int insert(HomeworktestInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table homeworktest
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	@InsertProvider(type = HomeworktestInfoSqlProvider.class, method = "insertSelective")
	int insertSelective(HomeworktestInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table homeworktest
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	@Select({ "select", "HT_ID, L_ID, HT_form, HT_introduction, HT_startTime, HT_endTime", "from homeworktest",
			"where HT_ID = #{HT_ID,jdbcType=DECIMAL}" })
	@Results({ @Result(column = "HT_ID", property = "HT_ID", jdbcType = JdbcType.DECIMAL, id = true),
			@Result(column = "L_ID", property = "L_ID", jdbcType = JdbcType.DECIMAL),
			@Result(column = "HT_form", property = "HT_form", jdbcType = JdbcType.VARCHAR),
			@Result(column = "HT_introduction", property = "HT_introduction", jdbcType = JdbcType.VARCHAR),
			@Result(column = "HT_startTime", property = "HT_startTime", jdbcType = JdbcType.DECIMAL),
			@Result(column = "HT_endTime", property = "HT_endTime", jdbcType = JdbcType.DECIMAL) })
	HomeworktestInfo selectByPrimaryKey(Integer HT_ID);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table homeworktest
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	@UpdateProvider(type = HomeworktestInfoSqlProvider.class, method = "updateByPrimaryKeySelective")
	int updateByPrimaryKeySelective(HomeworktestInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table homeworktest
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	@Update({ "update homeworktest", "set L_ID = #{L_ID,jdbcType=DECIMAL},", "HT_form = #{HT_form,jdbcType=VARCHAR},",
			"HT_introduction = #{HT_introduction,jdbcType=VARCHAR},",
			"HT_startTime = #{HT_startTime,jdbcType=DECIMAL},", "HT_endTime = #{HT_endTime,jdbcType=DECIMAL}",
			"where HT_ID = #{HT_ID,jdbcType=DECIMAL}" })
	int updateByPrimaryKey(HomeworktestInfo record);
}