package com.example.mapper;

import com.example.entity.LessonInfo;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface LessonInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lesson
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	@Delete({ "delete from lesson", "where L_ID = #{L_ID,jdbcType=DECIMAL}" })
	int deleteByPrimaryKey(Integer L_ID);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lesson
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	@Insert({ "insert into lesson (L_ID, CL_ID, ", "L_name, L_introduction, ", "L_startTime, L_endTime)",
			"values (#{L_ID,jdbcType=DECIMAL}, #{CL_ID,jdbcType=DECIMAL}, ",
			"#{L_name,jdbcType=VARCHAR}, #{L_introduction,jdbcType=VARCHAR}, ",
			"#{L_startTime,jdbcType=DECIMAL}, #{L_endTime,jdbcType=DECIMAL})" })
	int insert(LessonInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lesson
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	@InsertProvider(type = LessonInfoSqlProvider.class, method = "insertSelective")
	int insertSelective(LessonInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lesson
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	@Select({ "select", "L_ID, CL_ID, L_name, L_introduction, L_startTime, L_endTime", "from lesson",
			"where L_ID = #{L_ID,jdbcType=DECIMAL}" })
	@Results({ @Result(column = "L_ID", property = "L_ID", jdbcType = JdbcType.DECIMAL, id = true),
			@Result(column = "CL_ID", property = "CL_ID", jdbcType = JdbcType.DECIMAL),
			@Result(column = "L_name", property = "L_name", jdbcType = JdbcType.VARCHAR),
			@Result(column = "L_introduction", property = "L_introduction", jdbcType = JdbcType.VARCHAR),
			@Result(column = "L_startTime", property = "L_startTime", jdbcType = JdbcType.DECIMAL),
			@Result(column = "L_endTime", property = "L_endTime", jdbcType = JdbcType.DECIMAL) })
	LessonInfo selectByPrimaryKey(Integer L_ID);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lesson
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	@UpdateProvider(type = LessonInfoSqlProvider.class, method = "updateByPrimaryKeySelective")
	int updateByPrimaryKeySelective(LessonInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lesson
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	@Update({ "update lesson", "set CL_ID = #{CL_ID,jdbcType=DECIMAL},", "L_name = #{L_name,jdbcType=VARCHAR},",
			"L_introduction = #{L_introduction,jdbcType=VARCHAR},", "L_startTime = #{L_startTime,jdbcType=DECIMAL},",
			"L_endTime = #{L_endTime,jdbcType=DECIMAL}", "where L_ID = #{L_ID,jdbcType=DECIMAL}" })
	int updateByPrimaryKey(LessonInfo record);
}