package com.example.mapper;

import com.example.entity.ModuleInfo;
import org.apache.ibatis.jdbc.SQL;

public class ModuleInfoSqlProvider {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table module
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public String insertSelective(ModuleInfo record) {
		SQL sql = new SQL();
		sql.INSERT_INTO("module");
		if (record.getM_ID() != null) {
			sql.VALUES("M_ID", "#{M_ID,jdbcType=DECIMAL}");
		}
		if (record.getM_name() != null) {
			sql.VALUES("M_name", "#{M_name,jdbcType=VARCHAR}");
		}
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table module
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public String updateByPrimaryKeySelective(ModuleInfo record) {
		SQL sql = new SQL();
		sql.UPDATE("module");
		if (record.getM_name() != null) {
			sql.SET("M_name = #{M_name,jdbcType=VARCHAR}");
		}
		sql.WHERE("M_ID = #{M_ID,jdbcType=DECIMAL}");
		return sql.toString();
	}
}