package com.example.mapper;

import com.example.entity.OrdersInfo;
import org.apache.ibatis.jdbc.SQL;

public class OrdersInfoSqlProvider {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public String insertSelective(OrdersInfo record) {
		SQL sql = new SQL();
		sql.INSERT_INTO("orders");
		if (record.getID() != null) {
			sql.VALUES("ID", "#{ID,jdbcType=VARCHAR}");
		}
		if (record.getCL_ID() != null) {
			sql.VALUES("CL_ID", "#{CL_ID,jdbcType=DECIMAL}");
		}
		if (record.getO_Time() != null) {
			sql.VALUES("O_Time", "#{O_Time,jdbcType=DECIMAL}");
		}
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public String updateByPrimaryKeySelective(OrdersInfo record) {
		SQL sql = new SQL();
		sql.UPDATE("orders");
		if (record.getO_Time() != null) {
			sql.SET("O_Time = #{O_Time,jdbcType=DECIMAL}");
		}
		sql.WHERE("ID = #{ID,jdbcType=VARCHAR}");
		sql.WHERE("CL_ID = #{CL_ID,jdbcType=DECIMAL}");
		return sql.toString();
	}
}