package com.example.mapper;

import com.example.entity.OrdersInfo;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface OrdersInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	@Delete({ "delete from orders", "where ID = #{ID,jdbcType=VARCHAR}", "and CL_ID = #{CL_ID,jdbcType=DECIMAL}" })
	int deleteByPrimaryKey(@Param("ID") String ID, @Param("CL_ID") Integer CL_ID);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	@Insert({ "insert into orders (ID, CL_ID, ", "O_Time)",
			"values (#{ID,jdbcType=VARCHAR}, #{CL_ID,jdbcType=DECIMAL}, ", "#{O_Time,jdbcType=DECIMAL})" })
	int insert(OrdersInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	@InsertProvider(type = OrdersInfoSqlProvider.class, method = "insertSelective")
	int insertSelective(OrdersInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	@Select({ "select", "ID, CL_ID, O_Time", "from orders", "where ID = #{ID,jdbcType=VARCHAR}",
			"and CL_ID = #{CL_ID,jdbcType=DECIMAL}" })
	@Results({ @Result(column = "ID", property = "ID", jdbcType = JdbcType.VARCHAR, id = true),
			@Result(column = "CL_ID", property = "CL_ID", jdbcType = JdbcType.DECIMAL, id = true),
			@Result(column = "O_Time", property = "O_Time", jdbcType = JdbcType.DECIMAL) })
	OrdersInfo selectByPrimaryKey(@Param("ID") String ID, @Param("CL_ID") Integer CL_ID);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	@UpdateProvider(type = OrdersInfoSqlProvider.class, method = "updateByPrimaryKeySelective")
	int updateByPrimaryKeySelective(OrdersInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	@Update({ "update orders", "set O_Time = #{O_Time,jdbcType=DECIMAL}", "where ID = #{ID,jdbcType=VARCHAR}",
			"and CL_ID = #{CL_ID,jdbcType=DECIMAL}" })
	int updateByPrimaryKey(OrdersInfo record);
}