package com.example.mapper;

import com.example.entity.ResourcesInfo;
import org.apache.ibatis.jdbc.SQL;

public class ResourcesInfoSqlProvider {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table resources
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public String insertSelective(ResourcesInfo record) {
		SQL sql = new SQL();
		sql.INSERT_INTO("resources");
		if (record.getRE_ID() != null) {
			sql.VALUES("RE_ID", "#{RE_ID,jdbcType=DECIMAL}");
		}
		if (record.getL_ID() != null) {
			sql.VALUES("L_ID", "#{L_ID,jdbcType=DECIMAL}");
		}
		if (record.getRE_form() != null) {
			sql.VALUES("RE_form", "#{RE_form,jdbcType=VARCHAR}");
		}
		if (record.getRE_introduction() != null) {
			sql.VALUES("RE_introduction", "#{RE_introduction,jdbcType=VARCHAR}");
		}
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table resources
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public String updateByPrimaryKeySelective(ResourcesInfo record) {
		SQL sql = new SQL();
		sql.UPDATE("resources");
		if (record.getL_ID() != null) {
			sql.SET("L_ID = #{L_ID,jdbcType=DECIMAL}");
		}
		if (record.getRE_form() != null) {
			sql.SET("RE_form = #{RE_form,jdbcType=VARCHAR}");
		}
		if (record.getRE_introduction() != null) {
			sql.SET("RE_introduction = #{RE_introduction,jdbcType=VARCHAR}");
		}
		sql.WHERE("RE_ID = #{RE_ID,jdbcType=DECIMAL}");
		return sql.toString();
	}
}