package com.example.mapper;

import com.example.entity.ScInfo;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;

public interface ScInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sc
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	@Delete({ "delete from sc", "where STU_ID = #{STU_ID,jdbcType=VARCHAR}", "and CL_ID = #{CL_ID,jdbcType=DECIMAL}",
			"and ID = #{ID,jdbcType=VARCHAR}" })
	int deleteByPrimaryKey(@Param("STU_ID") String STU_ID, @Param("CL_ID") Integer CL_ID, @Param("ID") String ID);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sc
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	@Insert({ "insert into sc (STU_ID, CL_ID, ", "ID)",
			"values (#{STU_ID,jdbcType=VARCHAR}, #{CL_ID,jdbcType=DECIMAL}, ", "#{ID,jdbcType=VARCHAR})" })
	int insert(ScInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sc
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	@InsertProvider(type = ScInfoSqlProvider.class, method = "insertSelective")
	int insertSelective(ScInfo record);
}