package com.example.mapper;

import com.example.entity.TeacherInfo;
import org.apache.ibatis.jdbc.SQL;

public class TeacherInfoSqlProvider {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table teacher
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public String insertSelective(TeacherInfo record) {
		SQL sql = new SQL();
		sql.INSERT_INTO("teacher");
		if (record.getID() != null) {
			sql.VALUES("ID", "#{ID,jdbcType=VARCHAR}");
		}
		if (record.getUsername() != null) {
			sql.VALUES("username", "#{username,jdbcType=VARCHAR}");
		}
		if (record.getPasswords() != null) {
			sql.VALUES("passwords", "#{passwords,jdbcType=VARCHAR}");
		}
		if (record.getT_name() != null) {
			sql.VALUES("T_name", "#{T_name,jdbcType=VARCHAR}");
		}
		if (record.getT_sex() != null) {
			sql.VALUES("T_sex", "#{T_sex,jdbcType=CHAR}");
		}
		if (record.getT_Cnumber() != null) {
			sql.VALUES("T_Cnumber", "#{T_Cnumber,jdbcType=CHAR}");
		}
		if (record.getT_introduction() != null) {
			sql.VALUES("T_introduction", "#{T_introduction,jdbcType=VARCHAR}");
		}
		if (record.getT_IDcard() != null) {
			sql.VALUES("T_IDcard", "#{T_IDcard,jdbcType=CHAR}");
		}
		if (record.getT_QQ() != null) {
			sql.VALUES("T_QQ", "#{T_QQ,jdbcType=VARCHAR}");
		}
		if (record.getT_wei() != null) {
			sql.VALUES("T_wei", "#{T_wei,jdbcType=VARCHAR}");
		}
		if (record.getT_emile() != null) {
			sql.VALUES("T_emile", "#{T_emile,jdbcType=VARCHAR}");
		}
		if (record.getT_mobile() != null) {
			sql.VALUES("T_mobile", "#{T_mobile,jdbcType=DECIMAL}");
		}
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table teacher
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public String updateByPrimaryKeySelective(TeacherInfo record) {
		SQL sql = new SQL();
		sql.UPDATE("teacher");
		if (record.getUsername() != null) {
			sql.SET("username = #{username,jdbcType=VARCHAR}");
		}
		if (record.getPasswords() != null) {
			sql.SET("passwords = #{passwords,jdbcType=VARCHAR}");
		}
		if (record.getT_name() != null) {
			sql.SET("T_name = #{T_name,jdbcType=VARCHAR}");
		}
		if (record.getT_sex() != null) {
			sql.SET("T_sex = #{T_sex,jdbcType=CHAR}");
		}
		if (record.getT_Cnumber() != null) {
			sql.SET("T_Cnumber = #{T_Cnumber,jdbcType=CHAR}");
		}
		if (record.getT_introduction() != null) {
			sql.SET("T_introduction = #{T_introduction,jdbcType=VARCHAR}");
		}
		if (record.getT_IDcard() != null) {
			sql.SET("T_IDcard = #{T_IDcard,jdbcType=CHAR}");
		}
		if (record.getT_QQ() != null) {
			sql.SET("T_QQ = #{T_QQ,jdbcType=VARCHAR}");
		}
		if (record.getT_wei() != null) {
			sql.SET("T_wei = #{T_wei,jdbcType=VARCHAR}");
		}
		if (record.getT_emile() != null) {
			sql.SET("T_emile = #{T_emile,jdbcType=VARCHAR}");
		}
		if (record.getT_mobile() != null) {
			sql.SET("T_mobile = #{T_mobile,jdbcType=DECIMAL}");
		}
		sql.WHERE("ID = #{ID,jdbcType=VARCHAR}");
		return sql.toString();
	}
}