package com.example.mapper;

import com.example.entity.TeacherInfo;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface TeacherInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table teacher
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	@Delete({ "delete from teacher", "where ID = #{ID,jdbcType=VARCHAR}" })
	int deleteByPrimaryKey(String ID);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table teacher
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	@Insert({ "insert into teacher (ID, username, ", "passwords, T_name, ", "T_sex, T_Cnumber, T_introduction, ",
			"T_IDcard, T_QQ, T_wei, ", "T_emile, T_mobile)",
			"values (#{ID,jdbcType=VARCHAR}, #{username,jdbcType=VARCHAR}, ",
			"#{passwords,jdbcType=VARCHAR}, #{T_name,jdbcType=VARCHAR}, ",
			"#{T_sex,jdbcType=CHAR}, #{T_Cnumber,jdbcType=CHAR}, #{T_introduction,jdbcType=VARCHAR}, ",
			"#{T_IDcard,jdbcType=CHAR}, #{T_QQ,jdbcType=VARCHAR}, #{T_wei,jdbcType=VARCHAR}, ",
			"#{T_emile,jdbcType=VARCHAR}, #{T_mobile,jdbcType=DECIMAL})" })
	int insert(TeacherInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table teacher
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	@InsertProvider(type = TeacherInfoSqlProvider.class, method = "insertSelective")
	int insertSelective(TeacherInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table teacher
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	@Select({ "select", "ID, username, passwords, T_name, T_sex, T_Cnumber, T_introduction, T_IDcard, ",
			"T_QQ, T_wei, T_emile, T_mobile", "from teacher", "where ID = #{ID,jdbcType=VARCHAR}" })
	@Results({ @Result(column = "ID", property = "ID", jdbcType = JdbcType.VARCHAR, id = true),
			@Result(column = "username", property = "username", jdbcType = JdbcType.VARCHAR),
			@Result(column = "passwords", property = "passwords", jdbcType = JdbcType.VARCHAR),
			@Result(column = "T_name", property = "T_name", jdbcType = JdbcType.VARCHAR),
			@Result(column = "T_sex", property = "T_sex", jdbcType = JdbcType.CHAR),
			@Result(column = "T_Cnumber", property = "T_Cnumber", jdbcType = JdbcType.CHAR),
			@Result(column = "T_introduction", property = "T_introduction", jdbcType = JdbcType.VARCHAR),
			@Result(column = "T_IDcard", property = "T_IDcard", jdbcType = JdbcType.CHAR),
			@Result(column = "T_QQ", property = "T_QQ", jdbcType = JdbcType.VARCHAR),
			@Result(column = "T_wei", property = "T_wei", jdbcType = JdbcType.VARCHAR),
			@Result(column = "T_emile", property = "T_emile", jdbcType = JdbcType.VARCHAR),
			@Result(column = "T_mobile", property = "T_mobile", jdbcType = JdbcType.DECIMAL) })
	TeacherInfo selectByPrimaryKey(String ID);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table teacher
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	@UpdateProvider(type = TeacherInfoSqlProvider.class, method = "updateByPrimaryKeySelective")
	int updateByPrimaryKeySelective(TeacherInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table teacher
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	@Update({ "update teacher", "set username = #{username,jdbcType=VARCHAR},",
			"passwords = #{passwords,jdbcType=VARCHAR},", "T_name = #{T_name,jdbcType=VARCHAR},",
			"T_sex = #{T_sex,jdbcType=CHAR},", "T_Cnumber = #{T_Cnumber,jdbcType=CHAR},",
			"T_introduction = #{T_introduction,jdbcType=VARCHAR},", "T_IDcard = #{T_IDcard,jdbcType=CHAR},",
			"T_QQ = #{T_QQ,jdbcType=VARCHAR},", "T_wei = #{T_wei,jdbcType=VARCHAR},",
			"T_emile = #{T_emile,jdbcType=VARCHAR},", "T_mobile = #{T_mobile,jdbcType=DECIMAL}",
			"where ID = #{ID,jdbcType=VARCHAR}" })
	int updateByPrimaryKey(TeacherInfo record);
}