package com.example.mapper;

import com.example.entity.UsersInfo;
import org.apache.ibatis.jdbc.SQL;

public class UsersInfoSqlProvider {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public String insertSelective(UsersInfo record) {
		SQL sql = new SQL();
		sql.INSERT_INTO("users");
		if (record.getID() != null) {
			sql.VALUES("ID", "#{ID,jdbcType=VARCHAR}");
		}
		if (record.getUsername() != null) {
			sql.VALUES("username", "#{username,jdbcType=VARCHAR}");
		}
		if (record.getPasswords() != null) {
			sql.VALUES("passwords", "#{passwords,jdbcType=VARCHAR}");
		}
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbg.generated  Sun Jul 08 23:52:53 CST 2018
	 */
	public String updateByPrimaryKeySelective(UsersInfo record) {
		SQL sql = new SQL();
		sql.UPDATE("users");
		if (record.getUsername() != null) {
			sql.SET("username = #{username,jdbcType=VARCHAR}");
		}
		if (record.getPasswords() != null) {
			sql.SET("passwords = #{passwords,jdbcType=VARCHAR}");
		}
		sql.WHERE("ID = #{ID,jdbcType=VARCHAR}");
		return sql.toString();
	}
}